name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "dpw0616a.eastern-dawn.com", custom_domain = true },
  { pattern = "dpw0616b.eastern-dawn.com", custom_domain = true },
  { pattern = "dpw0616c.eastern-dawn.com", custom_domain = true },
  { pattern = "dpw0616d.eastern-dawn.com", custom_domain = true },
  { pattern = "dpw0616e.eastern-dawn.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "dpw0616f.eastern-dawn.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
